/**
 * Licensed Materials - Property of IBM
 * IBM Cognos Products: BI Cloud (C) Copyright IBM Corp. 2014, 2015
 * US Government Users Restricted Rights - Use, duplication or disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
 */
define({
	root: {
		//Menus
		"MENU_DRILL_TO_ROOT": "View all",
		"MENU_DRILL_UP" : "Drill up",
		"MENU_DRILL_DOWN" : "Drill down",
		"MENU_HIDE_COLUMN" : "Hide",
		"MENU_KEEP_COLUMN" : "Keep",
		"MENU_UNHIDE_ALL_COLUMN" : "Unhide all",
		"MENU_HIDE_ROW" : "Hide",
		"MENU_KEEP_ROW" : "Keep",
		"MENU_UNHIDE_ALL_ROW" : "Unhide all",
		"MENU_TOGGLEOVERVIEW" : "Show/hide overview",
		"MENU_SWAPAXES" : "Swap rows and columns",
		"MENU_SORT_ROW" : "Sort row values",
		"MENU_SORT_COLUMN" : "Sort column values",
		"MENU_KEEPANDEXCLUDE" : "Keep and exclude",
		"MENU_KEEP_AND_HIDE" : "Keep and hide",
		"MENU_DRILL" : "Drill",
		"MENU_SORT_BY_VALUE" : "Sort by value",
		"MENU_SORT_DATA_ASCENDING" : "Sort ascending",
		"MENU_SORT_DATA_DESCENDING" : "Sort descending",
		"MENU_SORT_DATA_HIERARCHY_ASCENDING" : "Ascending",
		"MENU_SORT_DATA_HIERARCHY_DESCENDING" : "Descending",
		"MENU_SORT_DATA_CLEAR" : "Clear sort",
		"MENU_SORT_BY_LABEL" : "Sort by label",
		"MENU_SORT_LABEL_ASCENDING" : "Sort ascending",
		"MENU_SORT_LABEL_DESCENDING" : "Sort descending",
		"MENU_SORT_LABEL_CLEAR" : "Clear sort",
		"MENU_SUPPRESS_COLUMN" : "Columns",
		"MENU_SUPPRESS_ROW" : "Rows",
		"MENU_SUPPRESS" : "Suppress zeros",
		"MENU_SHOW_TOTALS" : "Show totals",
		"MENU_SHOW_TOTALS_LEADING" : "Show totals leading",
		"MENU_SHOW_TOTALS_TRAILING" : "Show totals trailing",
		"MENU_SHOW_TOTALS_NONE" : "Hide totals",
		"MENU_RELEASE_COLUMN" : "Unsuppress zeros",
		"MENU_RELEASE_ROW" : "UnSuppress zeros",
		"MENU_SPREAD_CLEAR" : "Clear",
		"MENU_SPREAD_HOLD" : "Hold",
		"MENU_SPREAD_RELEASE_HOLD" : "Release hold",
		"MENU_SPREAD_RELEASE_ALL" : "Release all holds",
		"MENU_SUPPRESS_GRID" : "Suppress zeros",
		"MENU_RELEASE_GRID" : "Unsuppress zeros",
		"MENU_SHOWCELLVALUESMENUACTION" : "Show cell values as ...",
		"MENU_SHOW_CELL_VALUE_AS" : "Show cell values as ...",
		"MENU_SHOW_AS_CELLVALUE" : "As is",
		"MENU_SHOW_AS_PERCENT_ROW_TOTAL" : "% row total",
		"MENU_SHOW_AS_PERCENT_COLUMN_TOTAL" : "% column total",
		"MENU_SHOW_AS_PERCENT_PARENT_ROW_TOTAL" : "% parent row total",
		"MENU_SHOW_AS_PERCENT_PARENT_COLUMN_TOTAL" : "% parent column total",
		"MENU_SHOW_AS_PERCENT_GRAND_TOTAL" : "% grand total",
		"MENU_EXPAND_TO_LEVEL" : "Expand to level",
		"MENU_ADD_SUMMARY_WIDGET" : "Add to canvas",
		"MENU_SORT_HIERARCHY" : "Sort hierarchical",
		"MENU_RADIOFORM_ADVANCED":"Advanced",
		"MENU_SHOW_CELL_VALUE_AS_DESCRIPTION" :"Display the value that is entered in the cell",
		"MENU_SHOW_AS_PERCENT_ROW_TOTAL_DESCRIPTION" :"Displays the value in each row as a percentage of the total for the row.",
		"MENU_SHOW_AS_PERCENT_COLUMN_TOTAL_DESCRIPTION":"Displays all the values in each column as a percentage of the total for the column.",
		"MENU_SHOW_AS_PERCENT_GRAND_TOTAL_DESCRIPTION":"Displays values as a percentage of the grand total of all the values or data points in the report.",
		"MENU_SHOW_AS_PERCENT_PARENT_ROW_TOTAL_DESCRIPTION":"value for the item _________________ value for the parent item on columns",
		"MENU_SHOW_AS_PERCENT_PARENT_COLUMN_TOTAL_DESCRIPTION":"value for the item _________________ value for the parent item on rows",
		"MENU_RADIO_PREVIEW" : "Preview",
		"MENU_RADIO_OK" : "OK",
		"MENU_RADIO_CANCEL" : "Cancel",
		"MENU_SAVE_BUTTON" : "Save",
		"MENU_SAVE_AS_BUTTON" : "Save as",
		"MENU_SHARE_VIEW" : "Share",
		"MENU_CALCULATIONS" : "Calculations",
		"MENU_CALCULATION_CREATE" : "Create calculation...",
		"MENU_CALCULATION_RANK" : "Rank",
		"MENU_CALCULATION_ABSOLUTE_VALUE" : "Absolute value",
		"MENU_CALCULATION_SUMMARIZEALL" : "Summarize all...",
		"MENU_CALCULATION_PERCENT_OF_TOTAL" : "Percentage (%) of total",
		"MENU_CALCULATION_PERCENT_OF_PARENT" : "Percentage (%) of parent",
		"MENU_CALCULATION_PERCENT_OF" : "% Of",
		"MENU_CALCULATION_REMOVE": "Remove",
		"MENU_CALCULATION_RENAME": "Rename",
		"MENU_CALCULATION_PERCENT_CHANGE": "% of change",
		"MENU_CALCULATION_MULTIPLY": "Multiply",
		"MENU_CALCULATION_PLUS": "Plus",
		"MENU_CALCULATION_MINUS": "Minus",
		"MENU_CALCULATION_DIVIDE": "Divide",
		"MENU_CALCULATION_VAR": "Variance",
		"MENU_CALCULATION_SUM": "Sum",
		"MENU_CALCULATION_AVG": "Average",
		"MENU_CALCULATION_MEDIAN": "Median",
		"MENU_CALCULATION_STDEV": "Standard deviation",
		"MENU_CALCULATION_MAX": "Maximum",
		"MENU_CALCULATION_MIN": "Minimum",
		"MENU_CALCULATION_CREATE_MORE": "More",
		//Text
		"TEXT_CALCULATION_RANK" : "Calculates the rank across the %{axis} values",
		"TEXT_CALCULATION_ABSOLUTE_VALUE" : "Calculates the absolute value across the %{axis} values",
		"TEXT_CALCULATION_PERCENT_OF_TOTAL" : "Calculates the percentage of the total across the %{axis} values",
		"TEXT_CALCULATION_PERCENT_OF_PARENT" : "Calculates the percentage of the parent total across the %{axis} values",
		"TEXT_CALCULATION_PERCENT_OF" : "% Of",
		"TEXT_CALCULATION_PERCENT_CHANGE": "% of change",
		"TEXT_CALCULATION_MULTIPLY": "Multiplies the %{axis} values with <number>",
		"TEXT_CALCULATION_PLUS": "Adds the %{axis} values with <number>",
		"TEXT_CALCULATION_MINUS": "Subtracts the %{axis} values  with <number>",
		"TEXT_CALCULATION_DIVIDE": "Divides the %{axis} values with <number>",
		"TEXT_CALCULATION_AVERAGE": "Calculates the average of two members",
		"TEXT_CALCULATION_MINIMUM": "Calculates the minimum of two members",
		"TEXT_CALCULATION_MAXIMUM": "Calculates the maximum of two members",
		"TEXT_CALCULATION_MEDIAN": "Calculates the median of two members",
		"TEXT_CALCULATION_TWO_MEMBERS_MULTIPLY": "Calculates the multiplication of two members",
		"TEXT_CALCULATION_TWO_MEMBERS_PLUS": "Calculates the addition of two members",
		"TEXT_CALCULATION_TWO_MEMBERS_MINUS": "Calculates the subtraction of two members",
		"TEXT_CALCULATION_TWO_MEMBERS_DIVIDE": "Calculates the division of two members",
		"TEXT_CALCULATION_PERCENT_CHANGE": "Calculates the percentage difference of the two members",
		"TEXT_CALCULATION_PERCENT_OF": "Calculates the first member as a percentage of the second member",
		"TEXT_CALCULATION_THREE_MEMBERS_AVERAGE": "Calculates the average value of the members",
		"TEXT_CALCULATION_THREE_MEMBERS_MINIMUM": "Calculates the minimum value of the members",
		"TEXT_CALCULATION_THREE_MEMBERS_MAXIMUM": "Calculates the maximum value of the members",
		"TEXT_CALCULATION_THREE_MEMBERS_MEDIAN": "Calculates the median value of the members",
		"TEXT_CALCULATION_THREE_MEMBERS_SUM": "Calculates the summation value of the members",
		"TEXT_CALCULATION_ACROSS_VALUES": "Look across the %{axis} values",
		"TEXT_CALCULATION_ARITHMETIC": "Arithmetic",
		"TEXT_CALCULATION_SUMMARIZE": "Look across the %{axis} values",
		"TEXT_CALCULATION_PERCENTAGE": "Percentage",
		"TEXT_DYNAMIC_CALCULATION": "Creates a summary of the member values currrently shown in the set.\n\nNote, it summarizes the lowest level(visible) members in the hierarchy ",
		//Misc
		"LOADING" : "Loading...",
		"CANCEL" : "Cancel",
		"UNNAMED_SUBSET_TITLE" : "Selection",
		"EDITABLE_EDITOR_OK" : "Ok",
		"EDITABLE_EDITOR_CANCEL" : "Cancel",
		"POPUP_CONFIRMATION_OK" : "Ok",
		"POPUP_CONFIRMATION_CANCEL" : "Cancel",

		//Content Tree :
		"CONTENTTREE_LABEL_SERVERS" : "Servers",
		"MENU_ADD_DIMENSION":"Add dimension",
		"MENU_ADD_TM1ATTRCUBEMDV":"Edit dimension",
		"MENU_ADD_HIERARCHY_EDITOR":"Edit hierarchy",
		"MENU_ADD_TM1ATTRCUBEMDV_NEWTAB":"Edit dimension in new tab",
		"MENU_ADD_HIERARCHY_EDITOR_NEWTAB":"Edit hierarchy in new tab",
		"MENU_CREATE_DIMENSION" : "Create dimension",
		"MENU_DELETE_DIMENSION" : "Delete dimension",
		"MENU_DELETE_SUBSET" : "Delete set",
		"MENU_ADD_TM1MDV":"Add view",
		"MENU_RUN_PROCESS":"Run process",
		"MENU_CHECK_PROCESS":"Check process progress",
		"MENU_ADD_TM1WEB":"Add TM1 web view",
		"MENU_ADD_BLOB":"Add websheet",
		"MENU_ADD_SUBSET":"Add subset",
		"MENU_EDIT_SET":"Edit set...",
		"MENU_ADD_ITEM":"Add item",
		"MENU_ADD_EXPLOREPOINT":"Add explore point",
		"MENU_ADD_CUBE":"Add cube",
		"MENU_CREATE_VIEWER":"Add new view",
		"MENU_CREATE_TM1HIERARCHY":"Create hierarchy",
		"MENU_DELETE_TM1HIERARCHY":"Delete hierarchy",
		"MENU_ADD_BUTTERFLY_VIEW":"Add butterfly view",
		"MENU_ADD_DATA_WIDGET_VIEW":"Add as selector widget",
		"MENU_ADD_MEMBER":"Add member",
		"MENU_PASTE_MEMBER":"Paste member",
		"MENU_DELETE_MEMBER" : "Delete member",
		"MENU_CUT_MEMBER" : "Cut member",
		"MENU_COPY_MEMBER" : "Copy member",
		"MENU_MOVE_MEMBER" : "Move member",
		"MENU_EDIT_HIERARCHY": "Edit hierarchy",
		"MENU_MOVE_UP" : "Move up",
		"MENU_MOVE_DOWN" : "Move down",
		"MENU_MOVE_TOP" : "Move to top",
		"MENU_MOVE_BOTTOM" : "Move to bottom",
		'MENU_IMPORT_DATA':"Import data",
		'MENU_IMPORT_DIMENSIONS':"Import dimension",
		'MENU_IMPORT_CUSTOM':"Custom import",
		'MENU_IMPORT_EXISTING_CUBE':"Import into cube",
		'MENU_IMPORT_EXISTING_DIMENSION':"Import into dimension",
		'MENU_OPSCON':"Monitor",
		'MENU_CREATE_SERVER':"Manage Server",
		'MENU_RUN_SERVER':"Run Server",
		'MENU_STOP_SERVER':"Stop Server",
		'MENU_METRICS_CHART':"Add chart",
		'MENU_RULES_EDITOR' :"Edit rules",
		'MENU_PROCESS_EDITOR':"View process",
		'MENU_ADD_FAVORITE' : "Bookmark this",
		'MENU_REMOVE_FAVORITE':"Remove bookmark",
		"MENU_DELETE_FROM_CONSOLIDATION" : "Remove member from multiple parent",
		'CONTEXTDATAVLAUE' :"Current value",
		"LEVEL_SELECT_ALL" : "Level %{level}",
		"CELLS_SELECT_ALL" : "All cells",
		'MENU_HOLDANDRELEASE' :"Hold and release",
		'MENU_EDITVALUE' : "Value",

		//Clipboard
		'MENU_CLIPBOARD_CUT' : "Cut",
		"MENU_CLIPBOARD_CUT_DISABLED" : "use Ctrl-X to cut",
		'MENU_CLIPBOARD_COPY' : "Copy",
		"MENU_CLIPBOARD_COPY_DISABLED" : "use Ctrl-C to copy",
		'MENU_CLIPBOARD_PASTE' : "Paste",
		"MENU_CLIPBOARD_PASTE_DISABLED" : "use Ctrl-V to paste",

		//Toolbar Shelf
		"MENU_REFRESH" : "Refresh",
		"MENU_SAVE" : "Save",
		"MENU_EXPORT" : "Export",
		"MENU_EDIT_TITLE" : "Edit the title",
		"MENU_EXPORT_SLICE_TO_EXCEL" : "Export slice to Excel",
		"MENU_EXPORT_SNAPSHOT_TO_EXCEL" : "Export snapshot to Excel",
		"MENU_EXPORT_TO_PDF" : "Export to PDF",
		"MENU_RESET_DATA" : "Reset data",
		"MENU_REBUILD_WEBBOOK" : "Rebuild webbook",
		"MENU_REBUILD_WEBSHEET" : "Rebuild websheet",
		"MENU_AUTO_FIT_SELECTED_COLUMNS" : "Auto Fit Selected Columns",
		"MENU_SANDBOX" : "Sandbox",
		"MENU_SANDBOX_CREATE" : "Create sandbox",
		"MENU_SANDBOX_DELETE" : "Delete sandbox",
		"MENU_SANDBOX_COMMIT" : "Commit data",
		'MENU_SNAPCOMMAND':"Snap Commands",
		'MENU_CHANGEDISPLAY' : "Change display",
		'MENU_CHANGEVIZ' : "Change visualization",
		'MENU_REPORTS' : "Reports",
		'MENU_DYNAMIC_REPORT' : "Dynamic Report",
		'MENU_QUICK_REPORT' : "Quick Report",
		'MENU_EXPLORATION' : "Exploration",
		'MENU_CUSTOM_REPORT' : "Custom Report",

		//Change Visualizations View
		"visMetricsTypes" : "Metrics visualizations",
		"visGeneralTypes" : "General visualizations",
		"visMore" : "More...",
		"visMoreTooltip" : "More visualizations...",

		//Error
		"ERROR_MSG_ST0001" : "Show totals can not be executed for grid area \"%{area}\"",
		"ERROR_MSG_ST0002" : "Show totals can not execute with command parameter \"%{variant}\"",
		"ERROR_MSG_CMD0001" : "Could not perform command \"%{id}\". Error: \"%{error}\"",
		"ERROR_MSG_CMD_NO_TIGRESPEC" : "No specification argument specified.",
		"ERROR_MSG_CMD_NO_MODEL" : "No model argument specified.",
		"ERROR_MSG_CMD_NO_VIEW" : "No view argument specified.",
		"ERROR_MSG_CMD_NO_SERVERNAME" : "No servername argument specified.",
		"ERROR_MSG_CMD_NO_SOURCE_SERVERNAME" : "No source servername argument specified for command.",
		"ERROR_MSG_CMD_NO_URL" : "No URL argument specified.",
		"ERROR_MSG_CMD_INVALID_DRILL_TYPE" : "Invalid drill type \"%{type}\".",
		"ERROR_MSG_CMD_INVALID_DRILL_AREA" : "Invalid drill area \"%{area}\".",
		"ERROR_MSG_CMD_INVALID_DRILL_HIERARCHY" : "Unable to determine hierarchy from drill area \"%{area}\".",
		"ERROR_MSG_CMD_INVALID_SORT_AREA" : "Invalid sort area \"%{area}\".",
		"ERROR_MSG_CMD_INVALID_SHOWTOTALS_HIERARCHY" : "Unable to determine hierarchy for show totals using grid area \"%{area}\".",
		"ERROR_MSG_CMD_INVALID_SORTBYLABEL_HIERARCHY": "Unable to determine hierarchy for sort by label using grid area \"%{area}\".",
		'ERROR_MSG_CMD_INVALID_SORT_NOCELLTUPLE': "Unable to determine cell member data for sort by value.",
		'ERROR_MSG_CMD_NO_SANDBOX_ACTION' : "No sandbox action specified.",
		'ERROR_MSG_CMD_INVALID_SANDBOX_ACTION' : "Invalid sandbox action \"%{action}\".",
		'ERROR_MSG_CMD_SANDBOX_UNABLE_TO_DELETE' : "Unable to delete sandbox \"%{sandboxId}\".",
		'ERROR_MSG_CMD_SANDBOX_UNABLE_TO_CREATE_NONAME' : "No name specified for new sandbox.",
		'ERROR_MSG_CMD_SANDBOX_UNABLE_TO_SETACTIVE_NOSANDBOXES' : "No sandboxes available.",
		"ERROR_MSG_CMD_SANDBOX_MERGE" : "Unable to merge sandbox.\n%{reason}",
		"ERROR_MSG_CMD_SANDBOX_PUBLISH" : "Unable to publish sandbox \"%{sandbox}\".\n%{error}",
		"ERROR_MSG_CMD_SANDBOX_DISCARD" : "Unable to discard sandbox \"%{sandbox}\".\n%{error}",
		"ERROR_MSG_CMD_SANDBOX_UNLOAD" : "Unable to unload sandbox \"%{sandbox}\".\n%{error}",
		"ERROR_MSG_CMD_SANDBOX_LOAD" : "Unable to load sandbox \"%{sandbox}\".\n%{error}",
		"ERROR_MSG_CMD_SANDBOX_SETACTIVE" : "Unable to set to sandbox \"%{sandbox}\".\n%{error}",
		"ERROR_MSG_CMD_SANDBOX_DELETE" : "Unable to delete sandbox \"%{sandbox}\".\n%{error}",
		"ERROR_MSG_CMD_SANDBOX_CREATE" : "Unable to create sandbox \"%{sandbox}\".\n%{error}",
		"ERROR_MSG_CMD_SANDBOX_LIST" : "Unable to retrieve sandbox list.\n%{error}",
		"ERROR_MSG_CMD_SANDBOX_GET" : "Unable to retrieve sandbox \"%{sandbox}\".\n%{error}",
		"ERROR_MSG_CMD_SWAP" : "Unable to swap axis.\n%{error}",
		"ERROR_MSG_CMD_COMPUTE" : "Unable to refresh contents of widget.\n%{error}",
		"ERROR_MSG_CMD_DRILL" : "Unable to drill.\n%{error}",
		"ERROR_MSG_CMD_SHOWTOTALS" : "Unable to show totals.\n%{error}",
		"ERROR_MSG_CMD_COMPOSE" : "Unable to compose your request.\n%{error}",
		"ERROR_MSG_CMD_UPDATE_MULTIPLE_SELECTION":"That command cannot be applied to your current selections.",
		"ERROR_CMD_DELETE_DIMENSION" : "Unable to delete dimension \"%{dimension}\".\n%{error}",
		"ERROR_CMD_FETCH_SECURITY_MODELDATA" : "Unable to fetch security model data for  dimension \"%{dimension}\".\n%{error}",
		"ERROR_CMD_CREATEERROR_DIMENSION" : "Unable to create dimension \"%{dimension}\".\n%{error}",
		"ERROR_CMD_CREATE_DIMENSION" : "Please enter a valid dimension name.",
		"ERROR_CMD_DELETE_HIERARCHY" : "Unable to delete hierarchy \"%{hierarchy}\".\n%{error}",
		"ERROR_VALID_CREATE_NEW_HIERARCHYNAME" : "Please enter a valid hierarchy name.",
		'ERROR_MSG_CMD_SLICE_TO_MDX_INVALID': 'Invalid or missing command arguments \"%{msg}\".',

		'ERROR_MSG_DRAG_VALID_ITEM' : "Please drag valid item from tree to start.",
		'ERROR' : 'Error',
		'ERROR_MSG_METRICS_NO_VIZ_RAVESPEC' : "Unable to retrieve Metrics Visualization Spec",
		'ERROR_MSG_METRICS_DIAGRAM_NO_CUBES' : "Unable to create the content of this widget. The scorecarding diagram may have been removed or is inaccessible.",
		'ERROR_MSG_METRICS_DIAGRAM_NO_CUBES_ADMIN' : "Please contact your administrator to ensure you have sufficient rights to view this widget.",
		'ERROR_MSG_METRICS_HISTORY_NO_DATA' : "Please contact your system administrator.",
		'ERROR_MSG_METRICS_NO_RAVESPEC' : "No Rave spec found,",
		'ERROR_MSG_METRICS_NO_RAVESPEC_RENDER' : "could not be rendered",
		//Command Specific
		'ERROR_MSG_CMD_FETCHMODELDATA' : "Unable to fetch data.\n%{message}",
		'ERROR_MSG_CMD_INVALID_HIDE_TYPE': "Invalid hide type \"%{type}\".",
		'ERROR_MSG_CMD_HIERARCHY_INVALIDTYPE' : "Invalid hierarchy type \"%{type}\".",
		'ERROR_MSG_CMD_HIERARCHY_NODIMENSION' : 'No dimension specified for hierarchy change.',
		'ERROR_MSG_CMD_HIERARCHY_NOVARIANTURL': 'No URL mapping for hierarchy type \"%{type}\".',
		'ERROR_MSG_CMD_HIERARCHY_INVALIDDIMENSIONINFO' : 'Invalid dimension information specified for hierarchy change.',
		'ERROR_MSG_CMD_HIERARCHY_NOHIERARCHYID': 'Invalid or no hierarchy id specified for hierarchy change.',
		"ERROR_CMD_CREATEERROR_HIERARCHY" : "Unable to create hierarchy \"%{hierarchyName}\".\n%{error}",
		'ERROR_MSG_CMD_HIERARCHY':"Unable to modify the view hierarchy.\n%{error}",
		'ERROR_MSG_CMD_SHOWCELLVALUEAS_CREATE_ERROR' : "Error creating cell values.",
		'ERROR_MSG_CMD_SHOWCELLVALUEAS_INVALIDTYPE' : "Invalid show value as type \"%{type}\".",
		'ERROR_MSG_CMD_SHOWCELLVALUEAS_UNHANDLEDTYPE' : "Unhandled show value as type \"%{type}\".",
		'ERROR_MSG_CMD_SLICE_INVALIDTYPE': 'Invalid slice type \"%{type}\".',
		'ERROR_MSG_CMD_SLICE_NOVARIANTURL': 'No URL mapping for slice type \"%{type}\".',
		'ERROR_MSG_CMD_SLICE_INVALIDSTEPSARRAY': 'Invalid steps array for slice.',
		'ERROR_MSG_CMD_SORTBYLABEL_INVALIDTYPE': 'Invalid sort by label type \"%{type}\".',
		"ERROR_MSG_CMD_SORTBYLABEL": 'Unable to sort by label.\n%{error}',
		'ERROR_MSG_CMD_SORTBYVALUE_INVALIDTYPE': 'Invalid sort by value type \"%{type}\".',
		"ERROR_MSG_CMD_SORTBYVALUE": 'Unable to sort by value.\n%{error}',
		'ERROR_MSG_CMD_ZEROSUPPRESSION_INVALIDTYPE': 'Invalid zero suppression type \"%{type}\".',
		'ERROR_MSG_CMD_ZEROSUPPRESSION_NOVARIANTURL': 'No URL mapping for zero suppression type \"%{type}\".',
		"ERROR_MSG_CMD_ZEROSUPPRESSION" : "Unable to apply zero suppression.\n%{error}",

		"ERROR_MSG_CMD_CELLUPDATE" : "Unable to apply cell update.\n%{error}",
		"ERROR_MSG_CMD_CELLHOLD" : "Unable to hold cell.\n%{error}",
		"ERROR_MSG_CMD_CELLREALEASEHOLD" : "Unable to release hold.\n%{error}",
		"ERROR_MSG_CMD_CELLCLEAR" : "Unable to clear cell.\n%{error}",
		'ERROR_MSG_CMD_CELLPASTE': "Unable to paste cell(s).\n%{error}",
		'ERROR_MSG_CMD_NO_CLIPBOARD_ACCESS_CUT': "Cut to clipboard failed. Your browser did not allow clipboard access.",
		'ERROR_MSG_CMD_NO_CLIPBOARD_ACCESS_COPY': "Copy to clipboard failed. Your browser did not allow clipboard access.",
		'ERROR_MSG_CMD_NO_CLIPBOARD_ACCESS_PASTE': "Paste to clipboard failed. Your browser did not allow clipboard access.",
		'ERROR_MSG_CLIPBOARDPASTE_EXCEPTION': "Exception encountered. Paste failed.",
		'ERROR_MSG_CLIPBOARDCUT_EXCEPTION': "Exception encountered. Cut failed.",
		'ERROR_MSG_CLIPBOARDCOPY_EXCEPTION': "Exception encountered. Copy failed.",
		'ERROR_MSG_CLIPBOARD_GENERIC_ERROR': "Error performing clipboard action.",

		'ERROR_MSG_CLIPBOARD_PASTE_EXCEEDS_MAXIMUM_CELLS' : "You are trying to paste more than the maximum allowable cells of %{maximum}. Unable to perform clipboard action.",
		'ERROR_MSG_CLIPBOARD_NO_PASTE_DATA' : "No data to paste.",
		"ERROR_MSG_CMD_CELLUPDATE_INVALIDTYPE": 'Invalid cell update type \"%{type}\".',

		"ERROR_MSG_DESTROY_CELLSET": 'Unable to destroy cellset.\n%{error}',

		"ERROR_MSG_COMMAND_NOMODElSPECIFIED": 'No model specified in the command.',
		"ERROR_MSG_COMMAND_NOSERVERSPECIFIED": "No server specified in the command",

		'ERROR_MSG_CMD_SERVER_CAPABILITIES' : "Unable to retrieve the capabilities from the grid service. The client will not be able to determine support.",

		"ERROR_401_UNAUTHORIZED" : "Authentication failure using your credentials. Please reauthenticate and try again.",

		//Calculation command
		"ERROR_MSG_CMD_CALCULATION_NOOPERAND": "No Operands for calculation.",
		"ERROR_MSG_CMD_CALCULATION_INVALIDTYPE": "Invalid calculation type.",
		"ERROR_MSG_CMD_INVALID_CALCULATION_HIERARCHY": "No hierarchy for calculation.",
		"ERROR_MSG_CMD_INVALID_CALCULATION_INVALID_AREA": "Calculation can not be specified for area of grid.",
		"ERROR_MSG_CMD_CALCULATION": "Error executing calculation.\n%{error}",
		//Content Tree errors
		'ERROR_MSG_CMD_FETCHCONTENTTREEDATA': "Unable to fetch data for content tree.\n%{message}",
		"ERROR_MSG_CMD_FETCHDIMINENSIONITEMS": "Unable to fetch content for the item.\n%{message}",
        //Subset
		'ERROR_MSG_SUBSET_USED_IN_VIEW': "This subset cannot be deleted because it is used in an existing view.",
		// Upload
		"WA_AUTH_WINDOW_NAME": "IBM Watson Analytics Authorization",
		"WA_ENABLE_POPUPS": "Enable pop-up windows in your browser to authenticate with IBM Watson Analytics",
		"ERROR_MSG_CMD_CREATEDATASET": "Unable to create the data set.\n%{message}",
		"WA_DATASET": "data set", // Choose the location for the data set.
		"WA_SUGGESTED_NAME": "%{cube} - %{view}",
		"WA_UPLOAD_TITLE": "Transfer data set",// (%{rows} rows)",
		"WA_UPLOAD_BUTTON": "Transfer",
		"WA_MSG_SELECT_ENTER": "Select a location and enter a name.",
		"WA_MSG_SELECT": "Select a location.",
		"WA_MSG_ENTER": "Enter a name.",
		"WA_MSG_OVERWRITE": "Data set '%{name}' exists. Transfer will overwrite its contents.",
		"WA_MSG_CREATE": "Transfer will create and load the data set '%{name}'.",
		"WA_MSG_TRANSFERRING": "Transferring '%{name}'...",
		"WA_MSG_PREPARING": "Preparing transfer...",
		"WA_MSG_PROGRESS_MB": "%{rows}/%{maxRows} rows (%{MB} MB)",
		"WA_ERR_TOKEN": "Error %{httpStatusCode} fetching access token. %{errorMessage}",
		"WA_ERR_FOLDERS": "An error occurred while fetching the root folder information from IBM Watson Analytics.\n%{error}",
		"WA_ERR_CREATE_DATASET": "An error occurred while creating the data set in IBM Watson Analytics.\n%{error}",
		"WA_ERR_DELETE_CONTENT": "An error occurred while deleting the data set content in IBM Watson Analytics.\n%{error}",
		"WA_ERR_UPLOAD_DATASET": "An error occurred while uploading the data set to IBM Watson Analytics.\n%{error}",
		"WA_ERR_USER_INFO": "An error occurred while retrieving user information from IBM Watson Analytics.\n%{error}",

		//UI
		"DIMENSION_DROPZONE_ROW_LABEL" : "Drop row item here",
		"DIMENSION_DROPZONE_COLUMN_LABEL" : "Drop column item here",
		"DIMENSION_DROPZONE_CONTEXT_LABEL" : "Drop context item here",
		"GRID_COLUMNS_LABEL" : "Columns",
		"GRID_ROWS_LABEL" : "Rows",
		//METRICS
		"METRICS_STATUS_INCOMPLETE" : "Incomplete",
		"METRICS_STATUS_POOR" : "Poor",
		"METRICS_STATUS_AVERAGE" :" Average",
		"METRICS_STATUS_EXCELLENT" : "Excellent",
		"METRICS_TREND_GETTING_WORSE" : "Getting Worse",
		"METRICS_TREND_NO_CHANGE" : "No Change",
		"METRICS_TREND_GETTING_BETTER" : "Getting Better",
		"METRICS_TB_ZOOM_IN" : "Zoom In",
		"METRICS_TB_ZOOM_OUT" : "Zoom Out",
		"METRICS_TB_EXPAND_ALL" : "Expand All",
		"METRICS_TB_COLLAPSE_ALL" : "Collapse All",
		"METRICS_TB_LEGEND" : "Legend",
		"METRICS_IMPACT_POSITIVE" : "Positive",
		"METRICS_IMPACT_NEGATIVE" : "Negative",
		"METRICS_IMPACT_UNDEFINED" : "Undefined",
		"METRICS_STRATEGY_STATUS_CALCULATION" : "Status Calculation : ",
		"METRICS_STRATEGY_BUBBLEUP_GREEN" : "Most Positive Status",
		"METRICS_STRATEGY_BUBBLEUP_RED" : "Least Positive Status",
		"METRICS_STRATEGY_BUBBLEUP_MAJORITYRULES" : "Most Frequent Status",
		"METRICS_STRATEGY_NO_STATUS" : "No Status",

		//SETTINGS
		"SETTINGS_TITLE" : "Cube View Properties",
		"PROP_TABLE_STYLE" : "Table style",
		"PROP_TABLE_STYLE_RETURN" : "Table style",
		"PROP_TABLE_STYLE_THEME" : "Themes",
		"PROP_TABLE_STYLE_BLUE" : "Blue",
		"PROP_TABLE_STYLE_GREY" : "Grey",
		"PROP_TABLE_STYLE_HEADERS" : "Headers",
		"PROP_CUBEVIEW_FEATURE": "Data refresh",
		"PROP_CUBEVIEW_FEATURE_RETURN": "Data refresh",
		"PROP_CUBEVIEW_AUTOCALC" : "Refresh after each data change",
		"PROP_CUBEVIEW_CHART": "Chart options",
		"PROP_CUBEVIEW_CHART_RETURN": "Chart options",
		"PROP_CUBEVIEW_SHOWSUMMARYVALUES" : "Show summary values in chart",
		"PROP_CUBEVIEW_SET_EDITOR": "Set editor",
		"PROP_CUBEVIEW_SET_EDITOR_RETURN": "Set editor",
		"PROP_CUBEVIEW_SET_EDITOR_ALLOW": "Allow access to Set editor",
		"PROP_CUBEVIEW_SYNCHRONIZE": "Synchronize",
		"PROP_CUBEVIEW_SANDBOX_SYNCHRONIZE": "Synchronize Sandbox",
		"PROP_CUBEVIEW_SYNCHRONIZE_RETURN": "Synchronize",
		"PROP_CUBEVIEW_SYNCHRONIZED_OPTION" : "Synchronize dimensions",
		"PROP_DASHBOARD_SYNCHRONIZE": "Synchronization scope",
		"PROP_DASHBOARD_SYNCHRONIZE_RETURN": "Synchronization scope",
		"PROP_DASHBOARD_SYNCHRONIZE_BOOK": "Book",
		"PROP_DASHBOARD_SYNCHRONIZE_SHEET": "Sheet",
		"PROP_CUBEVIEW_HIDEROWSHEADER": "Hide row headers",
		"PROP_CUBEVIEW_HIDECOLSHEADER": "Hide column headers",

		// Properties from datawidget property manager
		"PROP_COLORPALETTE_CAPTION" : "Color Palettes",
		"PROP_HIDEAXISTITLES_CAPTION" : "Hide Axis Title Labels",
		"PROP_HIDEAXISTITLES_DESC" : "Hide the titles for the axes.",
		"PROP_ABBREVIATENUMBERS_CAPTION" : "Abbreviate Numbers",
		"PROP_ABBREVIATENUMBERS_DESC" : "Shorten numbers displayed in the visualization.",
		"PROP_HIDELEGEND_CAPTION" : "Hide Legend",
		"PROP_HIDELEGEND_DESC" : "Hide the legend.",
		"PROP_LEGENDPOSITION_CAPTION" : "Legend Position",
		"PROP_HIDETREEMAPLEAFLABELS_CAPTION" : "Hide Leaf Labels",
		"PROP_HIDETREEMAPLEAFLABELS_DESC" : "Hide the leaf labels.",
		"PROP_HIDEGRIDLINES_CAPTION" : "Hide Grid Lines",
		"PROP_HIDEGRIDLINES_DESC" : "Hide grid lines.",

		// Subset Editor
		"MENU_SUBSETREMOVE" : "Remove",
		"MENU_ADDELEMENTS" : "Add",
		"MENU_SUBSETKEEP" : "Keep",
		"MENU_SUBSETEXPAND" : "Expand",
		"MENU_SUBSETCOLLAPSE" : "Collapse",
		"MENU_MOVETOTOP" : "Move to top",
		"MENU_MOVEUP" : "Move up",
		"MENU_MOVEDOWN" : "Move down",
		"MENU_MOVETOBOTTOM" : "Move to bottom",
		"MENU_INSERT_OPTIONS" : "Default member insertion (%{insertoption})",
		"MENU_INSERT_SINGLE_MEMBER" : "Insert member only",
		"MENU_INSERT_MEMBER_WITHCHILDREN" : "Insert member with children",
		"MENU_INSERT_MEMBER_WITHDESCENDANTS" : "Insert member with descendants",
		"MENU_INSERT_MEMBER_WITHINPUTS" : "Insert member with leaf nodes",
		"MENU_INSERT_MEMBER_WITHANCESTORS" : "Insert member with ancestors",
		"MENU_SET_SAVE" : "Save...",
		"MENU_SET_APPLY_CLOSE" : "Apply and close",
		"MENU_SETEDITOR_CLOSE" : "Close",
		"MENU_EDITSET" : "Edit set...",
		"MENU_WA_UPLOAD" : "Transfer data set to IBM Watson Analytics",
		"SET_EDITOR_SUBTITLE" : "Edit Set",
		"SET_EDITOR_TITLE" : "Dimension: %{dimensionname}",
		"SET_TIP_SEARCH" : "Search",
		"SET_TIP_CLEAR_SEARCH" : "Clear search",
		"SET_SAVE_TITLE" : "Save set as",
		"SET_SAVE_PART_OF" : "Part of ",
		"SET_SAVE_NAME" : "Name",
		"SET_SAVE_SHARE_PUBLIC" : "Share public",
		"SET_OK" : "OK",
		"SET_SAVE" : "Save",
		"SET_CANCEL" : "Cancel",
		"SET_CURRENT_SET" : "Current Set",
		"SET_AVAILABLE_MEMBERS" : "Available Members",
		"SET_SEARCH_AVAILABLE_MEMBERS" : "Search available members",
		"SET_SEARCH_QUICKSEARCH" : "Search now",
		"SET_SEARCH_SHOW_FILTERS" : "Show more",
		"SET_SEARCH_HIDE_FILTERS" : "Hide",
		"SET_OVERWRITE_EXISTING_SET" : "Overwrite existing set?",
		"SET_NAME_EXISTING" : "This name \"%{setname}\" already exists.",
		"SET_DO_YOU_WANT_OVERWRITE" : "Do you want to overwrite it?",
		"SET_DEFACLT_MEMBER_INSERTION" : "Default member insertion",
		"SET_DEFACLT_MEMBER_INSERTION_DESC":"When inserting a member, include the follow",
		"SET_INSERT_OPTION_MEMBERONLY" : "Member only",
		"SET_INSERT_OPTION_CHILDREN" : "Children",
		"SET_INSERT_OPTION_DESCENDANTS" : "Descendants",
		"SET_INSERT_OPTION_LEAFNODES" : "Leaf nodes",
		"SET_INSERT_OPTION_ANCESTORS" : "Ancestors",
		"SET_REPLACE_ALL_MEMBERS":"Replace all members",
		"SET_SEARCH_NAME" : "Name",
		"SET_SEARCH_LEVEL" : "Level",
		"SET_SEARCH_ATTRIBUTES" : "Attributes",
		"SET_SEARCH_CONTAINS" : "Contains",
		"SET_SEARCH_INPUT_PLACEHOLDER" : "Enter a keyword",
		"SET_SEARCH_ADD" : "Add filter",
		"SET_SEARCH_SEARCH" : "Search",
		"SET_SEARCH_CLEAR" : "Clear",
		"SET_MEMBERS_SET" : "Members (%{setname})",
		"SET_ALL_MEMBERS_SET" : "All members (%{hierarchyname})",
		"SET_MEMBERS_IN_SET_SETNAME" : "Members in set (%{setname})",
		"SET_SEARCH_RESULTS_SETNAME" : "Search results (%{name})",
		"SET_REMOVE_ALL" : "Remove all members",
		"SET_INSERT_ALL" : "Insert all",
		"SET_SELECT_AVAILABLE_HIERARCHY" : "Select available hierarchy",
		"SET_ALREADY_ACTIVE_HIERARCHIES" : "Already active hierarchies",
		"SET_HIERARCHY_NONE" : "&lt;None&gt;",
		"SET_MEMBERS_TO_VIEW" : "Select members to view",
		"SET_ALL_MEMBERS_FROM_HIERARCHY" : "All members from hierarchy",
		"SET_MEMBERS_FROM_EXISTING_SET" : "Members from existing set:",
		"SET_ALL_MEMBERS" : "All members",
		"SET_SELECT_ALL" : "Select all members",
		"SET_DESELECT_ALL" : "Deselect all",
		"SET_ALIAS" : "Alias",
		"SET_DISPLAY_ALIAS" : "Display alias (%{alias})",
		"SET_DISPLAY_ALIAS_NONE" : "Display alias (none)",
		"SET_SELECT_ALIAS" : "Select alias",
		"SET_NO_ALIAS" : "No alias",
		"SET_SHOW_HIDE_ATTRIBUTES" : "Show attributes",
		"SET_INSERT" : "Insert",
		"SET_REPLACE_ALL" : "Replace set with new insertion",
		"SET_SELECT_ATTRIBUTES" : "Show up to two attributes",
		"SET_SELECT_ATTRIBUTES_DESC" : "The sequence in which you select the attributes determines their order.",
		"SET_CLEAR_ALL" : "Clear all",
		"SET_MAKE_STATIC" : "Convert to snapshot",
		"SET_SHOW_SET_AS" : "Show set as",
		"SET_HIERARCHY_VIEW" : "Show set as (Hierarchy view)",
		"SET_DEFINITION_VIEW" : "Show set as (Definition view)",
		"SET_OPEN_MDX_EDITOR" : "Edit MDX",
		"SET_EDIT_MDX" : "Edit MDX",
		"SET_MDX_EDITOR_ERROR_TITLE" : "MDX Editor",
		"SET_MDX_EDITOR_ERROR" : "Error",
		"SET_EDIT_UNDO" : "Undo",
		"SET_EDIT_REDO" : "Redo",
		"SET_EDIT_WRAP_ON" : "Wrap on",
		"SET_EDIT_WRAP_OFF" : "Wrap off",
		"SET_FIND" : "Find",
		"SET_FIND_PLACEHOLDER" : "Find",
		"SET_FIND_NEXT" : "Next",
		"SET_FIND_PREV" : "Previous",
		"SET_SORT_ASC" : "Ascending",
		"SET_SORT_DESC" : "Descending",
		"SET_DIALOG_TITLE" : "Set Editor",
		"SET_CURRENTSET_NO_MEMBERS" : "There are no members in the current set.",
		"SET_SORT" : "Sort",
		"SET_SORT_HIERARCHICALLY" : "Sort hierarchically",
		"SET_LABEL_PRIVATE" : "Private",
		"SET_SAVE_FAIL" : "The set '%{setname}' is not saved successfully.\n%{message}",
		"SET_LOAD_CURRENT_SET_FAIL" : "The current set is not loaded successfully.\n%{message}",
		"SET_INVALID_MDX" : "Invalid MDX expression.",
		"SET_FAIL_LOAD_ATTRIBUTES" : "Failed to load attributes.\n%{message}",
		"SET_FAIL_EXPAND" : "Failed to expand the member.",
		"SET_FAIL_COLLAPSE" : "Failed to collapse the member.",
		"SET_INVALID_MEMBER" : "Invalid member.",
		"SET_FAIL_RUN_COMMAND" : "Failed to run command: %{command}.",
		"SET_FAIL_INSERT_MEMBER" : "Failed to insert members.",
		"SET_FAIL_REPLACE_ALL" : "Failed to replace all members.",
		"SET_FAIL_FILTER_MEMBERS" : "Failed to filter members.",
		"SET_FAIL_CHANGE_ALIAS" : "Failed to change alias.",
		"SET_FAIL_CHANGE_VIEW_MODE" : "Failed to change the current set's view.",
		"SET_FAIL_APPLY_MDX" : "Failed to apply the MDX.",
		"SET_FAIL_SORT_MEMBERS" : "Failed to sort members.",
		"SET_FAIL_POPULATE_SETS" : "Failed to populate sets.\n%{message}",
		"SET_FAIL_POPULATE_HIERARCHY" : "Failed to populate hierarchies.\n%{message}",
		"SET_FAIL_REMOVE_ALL_MEMBERS" : "Failed to remove all members.",
		"SET_PASTE_NO_VALUES_SPECIFIED" : "No values specified for paste.",
		"SET_FAIL_MAKE_STATIC": "Failed to convert set to a snapshot.",
		"SET_SHOW_TOTALS_LEADING": "Show Totals Leading",
		"SET_SHOW_TOTALS_TRAILING": "Show Totals Trailing",
		"SET_FAIL_TOGGLE_EXPAND_ABOVE": "Failed to toggle \"Show Totals\" mode.",
		//Dimension Editor
		"DIM_EDITOR_HIERARCHY_PANE":"Hierarchy",
		"DIM_EDITOR_ATTRIBUTES_PANE":"Member Attributes",
		"DIM_EDITOR_ATTRIBUTES_PANE_SECURITY":"Member Security",
		"DIM_EDITOR_INFO_TIP": "Show Information Panel",
		"DIM_EDITOR_INFO_TIP_HIDE": "Hide Information Panel",
		"DIM_EDITOR_ATTRIBUTE_TIP":"Switch to Member Attribute Mode",
		"DIM_EDITOR_SHOW_ATTRIBUTES":"Show Attributes",
		"DIM_EDITOR_HIDE_ATTRIBUTES":"Hide Attributes",
		"DIM_EDITOR_SHOW_GROUPS":"Show Groups",
		"DIM_EDITOR_HIDE_GROUPS":"Hide Groups",
		"DIM_EDITOR_SECURITY_TIP":"Switch to Member Security Mode",
		"DIM_EDITOR_EDIT_DIMENSION": "Edit Dimension",
		"DIM_EDITOR_FIND_MEMBER": "Search Members",
		"DIM_EDITOR_SORT_LEAF_MEMBERS": "Sort leaf members",
		"DIM_EDITOR_SORT_ASCENDING": "Sort ascending",
		"DIM_EDITOR_SORT_DESCENDING": "Sort descending",
		"DIM_EDITOR_SORT": "Sort",
		"DIM_EDITOR_SORT_HIERARCHY_ASCENDING" : "Hierarchical ascending",
		"DIM_EDITOR_SORT_HIERARCHY_DESCENDING" : "Hierarchical descending",
		"DIM_EDITOR_SORT_BY_DEFAULT" : "Sort by default",
		"DIM_EDITOR_SORT_MEMBERS" : "Sort members",
		"DIM_EDITOR_EXPANDALL_COLLAPSEALL": "Expand all/Collapse all",
		"DIM_EDITOR_SELECTALL_DESELECTALL": "select all/deselect all",
		"DIM_EDITOR_TOGGLE": "Toggle",
		"DIM_EDITOR_UPDATE" : "Automatically update index order",
		"DIM_EDITOR_UPDATING_INDEX_ORDER" : "Updating index order" ,
		"DIM_EDITOR_ATTRIBUTE_BASED_HIERARCHY" : "Attribute-based hierarchy",
		"DIM_EDITOR_MEMBERS_PANE":"Members",
		"DIM_EDITOR_DIMENSION_SAVE" : "Save",
		"DIM_EDITOR_DIMENSION_SAVE_AS" : "Save as...",
		"DIM_EDITOR_DIMENSION_CANCEL" : "Cancel",
		"DIM_EDITOR_DIMENSION_OK" : "ok" ,
		"DIM_EDITOR_DIMENSION_APPLY" : "Apply" ,
		"DIM_EDITOR_HIERARCHY_REGION" : "Hierarchy: ",
		"DIM_EDITOR_DELETE_HIERARCHY" : "Delete Hierarchy",
		"DIM_EDITOR_DELETE_DIMENSION" : "Delete Dimension",
		"DIM_EDITOR_DUPLICATE_HIERARCHY" : "Duplicate Hierarchy",
		"DIM_EDITOR_EDIT_HIERARCHY" : "Rename",
		"DIM_EDITOR_NEW_HIERARCHY" : "New Hierarchy",
		"DIM_EDITOR_LEAF_TAB" : "Leaf",
		"DIM_EDITOR_BLANK_HIERARCHY" : "Blank hierarchy",
		"DIM_EDITOR_FROM_ATTRIBUTES" : "From attribute..",
		"DIM_EDITOR_NEW_MEMBER" : "Enter new member",
		"DIM_EDITOR_OK": "OK",
		"DIM_EDITOR_CANCEL": "CANCEL",
		"DIM_EDITOR_CANCEL_BUTTON": "Cancel",
		"DIM_EDITOR_SELECT_ATTRIBUTE": "Select attributes for new hierarchy",
		"DIM_EDITOR_SELECT_ATTRIBUTE_SUBHEADER": "Select the attribute to base your new hierarchy on",
		"DIM_EDITOR_AVAILABLE_ATTRIBUTE": "Available attributes",
		"DIM_EDITOR_HIERARCHY_ATTRIBUTE": "Attributes for hierarchy",
		"DIM_EDITOR_ATTRIBUTE_OPTIONS": "Attribute Options",
		"DIM_EDITOR_CREATE_ATTRIBUTE": "Create new attribute",
		"DIM_EDITOR_CREATE_ATTRIBUTE_HEADER": "Create attribute",
		"DIM_EDITOR_REORDER_ATTRIBUTE": "Reorder attributes",
		"DIM_EDITOR_SORT_ATTRIBUTE": "Sort attributes",
		"DIM_EDITOR_ATTRIBUTE_NAME": "Attribute name",
		"DIM_EDITOR_ATTRIBUTE_PLACEHOLDER": "Type an attribute name",
		"DIM_EDITOR_ATTRIBUTE_TYPE": "Attribute type",
		"DIM_EDITOR_ATTRIBUTE_TYPE_TEXT": "Text",
		"DIM_EDITOR_ATTRIBUTE_TYPE_NUMBER": "Number",
		"DIM_EDITOR_ATTRIBUTE_TYPE_ALIAS": "Alias",
		"DIM_EDITOR_ATTRIBUTE_REORDER_PLACEHOLDER": "Start typing to find an attribute",
		"DIM_EDITOR_SELECT_ATTRIBUTE_FOR_DELETE": "Please select an attribute to delete.",
		"DIM_EDITOR_MOVE_TO_TOP": "Move to top",
		"DIM_EDITOR_MOVE_UP": "Move up",
		"DIM_EDITOR_MOVE_DOWN": "Move down",
		"DIM_EDITOR_MOVE_TO_BOTTOM": "Move to bottom",
		"DIM_EDITOR_NUMBER_OF_ITEMS": "Number of items:",
		"DIM_EDITOR_VIEWACTIONS_POPUP_HEADER": "View Actions",
		"DIM_EDITOR_VIEWACTIONS_POPUP_SUBHEADER": "These actions change the view",
		"DIM_EDITOR_VIEWACTIONS_POPUP_FILTER": "Filter...",
		"DIM_EDITOR_VIEWACTIONS_POPUP_SORT": "Sort...",
		"DIM_EDITOR_VIEWACTIONS_POPUP_APPLYCHANGES": "Apply changes to index",
		"DIM_EDITOR_VIEWACTIONS_POPUP_DISCARD": "Discard Changes",
		"DIM_EDITOR_NEW_HIERARCHY_PLACEHOLDER": "Type in name",
		"DIM_EDITOR_ATTR_HEADER": "Attribute Actions",
		"DIM_EDITOR_ATTR_CELL_HEADER": "Attribute cell actions",
		"DIM_EDITOR_ATTR_REMOVE": "Remove",
		"DIM_EDITOR_ATTR_EDIT": "Edit",
		"DIM_EDITOR_ATTR_EDIT_HEADER": "Edit Attribute",
		"DIM_EDITOR_ATTR_DELETE_HEADER": "Delete attribute",
		"DIM_EDITOR_ATTR_EDIT_PLACEHOLDER": "Attribute name",
		"DIM_EDITOR_ATTR_FIND": "Find an attribute value",
		"DIM_EDITOR_ATTR_ALIAS": "Set as default alias",
		"DIM_EDITOR_ATTR_HIERARCHY": "New hierarchy",
		"DIM_EDITOR_ATTR_REMOVE_CONFIRM": "Are you sure you want to remove the selected attribute",
		"DIM_EDITOR_ATTRS_REMOVE_CONFIRM": "Are you sure you want to remove the selected attributes",
		"DIM_EDITOR_HIERARCHY_CONFIRM_TITLE": "Create Hierarchy Warning",
		"DIM_EDITOR_HIERARCHY_CONFIRM_MESSAGE_V1": "Are you sure you want to create a new hierarchy from this attribute?",
		"DIM_EDITOR_ATTR_FIND_PLACEHOLDER": "Enter text",
		"DIM_EDITOR_MEMBER_ACTION_PASTE" : "Paste",
		"DIM_EDITOR_MEMBER_ACTION_ADDMEMBER" : "Add Member",
		"DIM_EDITOR_MEMBER_ACTION_REMOVEMEMBER" : "Remove",
		"DIM_EDITOR_MEMBER_ACTION_MOVEMEMBER" : "Move",
		"DIM_EDITOR_MEMBER_ACTION_BRANCHOFF" : "Branch Off",
		"DIM_EDITOR_REMOVE_FROM_PARENT_HIERARCHY" : "Remove from parent in hierarchy",
		"DIM_EDITOR_REMOVE_FROM_HIERARCHY" : "Remove from hierarchy",
		"DIM_EDITOR_DELETE_FROM_DIMENSION" : "Delete from dimension",
		"DIM_EDITOR_KEEP_IN_HIERARCHY" : "Keep in hierarchy",
		"DIM_EDITOR_COPYSPECIAL" : "Copy special",
		"DIM_EDITOR_RENAME" : "Rename",
		"DIM_EDITOR_CREATE_NEW_HIERARCHY" : "Create New Hierarchy",
		"DIM_EDITOR_COPY" : "Copy",
		"DIM_EDITOR_PASTE" : "Paste",
		"DIM_EDITOR_EDIT_ROW" : "Edit row",
		"DIM_EDITOR_CUT" : "Cut",
		"DIM_EDITOR_ADD_ABOVE" : "Add above",
		"DIM_EDITOR_ADD_BELOW" : "Add below",
		"DIM_EDITOR_ADD_AS_CHILD" : "Add as a child",
		"DIM_EDITOR_ADD_AS_PARENT" : "Add as a parent",
		"DIM_EDITOR_ATTR_INDEX_HEADER" : "Index Actions",
		"DIM_EDITOR_ATTR_INDEX_FIND": "Find an index number",
		"DIM_EDITOR_ATTR_ENTER_VAL": "Enter Values",
		"DIM_EDITOR_ALL_LEAF_MEMBERS" : "All leaf members",
		"DIM_EDITOR_ATTR_NOT_FOUND": "Attribute value not found",
		"DIM_EDITOR_ERROR_MESSAGE_HEADER": "Sorry, something went wrong.",
		"DIM_EDITOR_STRINGTYPE_ERROR": "This dimension does not have any string type attribute.. so no hierarchy can be created",
		"DIM_EDITOR_CREATE_DIMENSION": "Create New Dimension",
		"DIM_EDITOR_CREATE_PLACEHOLDER": "Type new %{typeToCreate} name here",
		"DIM_EDITOR_CREATE_HIERACHY_PLACEHOLDER": "hierarchy",
		"DIM_EDITOR_CREATE_DIMENSION_PLACEHOLDER": "dimension",
		"DIM_EDITOR_UNHIDE_ALL_COLUMN": "Unhide all attributes",
		"DIM_EDITOR_OPEN_DIMENSION_WIDGET_CHECKBOX": "   Open the new dimension in a dimension editor",
		"DIM_EDITOR_CREATE_DIMENSION_CREATEBTN": "Create",
		"DIM_EDITOR_CREATE_DIMENSION_CLOSEBTN": "Close",
		"DIM_EDITOR_EXPORT_TEXT": "Export to Text",
		"DIM_EDITOR_EXPORT_EXCEL": "Export to Excel",
		"DIM_EDITOR_HIERARCHY_SUCCESS": "Hierarchy '%{hierarchyName}' created successfully",
		"DIM_EDITOR_HIERARCHY_ERROR": "Hierarchy '%{hierarchyName}' already exists",
		"DIM_EDITOR_HIERARCHY_CREATE_ERROR": "Unable to create hierarchy",
		"DIM_EDITOR_OPEN_HIERARCHY_WIDGET_CHECKBOX": "   Open the new hierarchy in a dimension editor",
		"DIMENSION_IN_USE" : "Dimension is being used by a cube.",
		"DIMENSION_DELETE_SUCCESS" : "Dimension \"%{dimension}\" successfully deleted.",
		"DIM_EDITOR_HIERARCHY_DELETE_CONFIRM" : "Are you sure you want to delete this hierarchy \"%{hierarchyName}\" ?",
		"DIM_EDITOR_DIMENSION_DELETE_CONFIRM" : "Any hierarchies and their member sets associated with this dimension \"%{dimensionName}\" will be removed. This action can not be undone. Are you sure you want to delete this dimension?",
		"DIM_EDITOR_INSERT_MEMBER_FAILED" : "Failed to insert member \"%{memberName}\".\n%{error}",
		"DIM_EDITOR_DIMENSION_SUCCESS": "Dimension '%{dimensionName}' created successfully",
		"DIM_EDITOR_CREATE_DIM_HIER_FAIL": "Creation of %{typeToCreate} '%{createName}' failed.\n%{error}",
		"DIM_EDITOR_EMPTY" : "There are no dimensions to edit on this server, create a new dimension or switch servers",
		"DIM_EDITOR_MEMBERS_EMPTY_CMD_SORT": 'There are no members for dimension \"%{dimension}\". Unable to sort attributes.',
		"DIM_EDITOR_DELETE_MEMBERS_FROM_DIMENSION_WARNING" : "Member \"%{member}\" removed from the selected hierarchies for dimension \"%{dimension}\".",
		"ERROR_MSG_CMD_FIND_PARENTS" : "Excecuting Find Parents Command Failed.",
		"ERROR_MSG_EXECUTE" : "Excecute Command",
		"ERROR_MSG_CMD_DELETE_MEMBERS_FOR_HIERARCHY" : "Excecuting Delete Command Failed.",
		"DIM_EDITOR_DELETE_MEMBERS_FROM_DIMENSION_MESSAGE" : "Removing member \"%{member}\" from dimension \"%{dimension}\" will result in loss of all data associated with this member in all cubes. Do you wish to proceed?.",
		"DIM_EDITOR_LIST_PARENTS_LABEL" : "Select Parents from which the member will be removed",
		"DIM_EDITOR_LIST_HIERARCHIES_LABEL" : "Select Hierarchies from which the member will be removed",
		"DIM_EDITOR_DELETE_MEMBERS_MESSAGE" : "Member \"%{member}\" removed from hierarchy \"%{hierarchy}\". ",
		"DIM_EDITOR_DELETE_MEMBERS_MESSAGE_MULTHIERARCHY" : "Member remains in the \"%{allLeavesHiearchy}\" hierarchy.",
		"DIM_EDITOR_DELETE_MEMBERS_FROM_PARENTIN_HIERARCHY_MESSAGE" : "Member \"%{member}\" removed from the selected parents in \"%{hierarchy}\".",
		"DIM_EDITOR_DELETE_MEMBERS_FROM_SINGLE_PARENT_MESSAGE" : "Member \"%{member}\" removed from its parent in \"%{hierarchy}\".",
		"DIM_EDITOR_UNABLE_TO_CHANGE_CONSOLIDATION" : "Attempt to change a consolidated member without children to a leaf member failed. This can happen if there is a consolidation member with the same name in a different hierarchy.",
		"DIM_EDITOR_DELETE_MEMBERS_NO_PARENT_HIERARCHY_MESSAGE" : "Member \"%{member}\" cannot be removed.",
		"DIM_EDITOR_DELETE_MEMBERS_LABEL": "Delete member",
		"DIM_EDITOR_COMMAND_FAILED": "Failed.",
		"DIM_EDITOR_SEARCH_MEMBERS_NOT_FOUND": "Could not find Member '%{memberName}'.",
		"DIM_EDITOR_CANNOT_DELETE_DEFAULT_HIERARCHY": "Default hierachy \"%{hierarchyName}\" cannot be deleted.",
		"DIM_EDITOR_INVALID_URL" : "Invalid url",
		"DIM_EDITOR_ADD_WIDGET_MESSAGE": "The check Box to add the widget to canvas is disabled as you are not in authoring mode.",
		"DIM_EDITOR_CANNOT_DELETE_HIERARCHY_EDIT" : "Cannot delete hierarchies while you are editing the dimension \"%{dimension}\".",
		"DIM_EDITOR_CANNOT_CREATE_HIERARCHY_EDIT" : "Cannot create a hierarchy while you are editing the dimension \"%{dimension}\".",
		"DIM_EDITOR_CREATE_GROUP_HEADER" : "Create user group",
		"DIM_EDITOR_CREATE_NEW_GROUP" : "Create New User Group",
		"DIM_EDITOR_CREATE_GROUP_PLACEHOLDER" : "group",
		"DIM_EDITOR_UNABLE_TO_CREATE_GROUP" : "Unable to create user group, \"%{group}\".  %{error}",
		"DIM_EDITOR_DELETE_GROUP_HEADER" : "Delete user group",
		"DIM_EDITOR_GROUPS_REMOVE_CONFIRM" :"Are you sure you want to remove the selected user groups",
		"DIM_EDITOR_GROUP_REMOVE_CONFIRM" :"Are you sure you want to remove the selected user group",
		"DIM_EDITOR_SELECT_GROUP_FOR_DELETE" : "Please select a user group to delete.",
		"DIM_EDITOR_UNABLE_TO_DELETE_GROUP" : "Unable to remove the selected user group(s).  %{error}",
		"DIM_EDITOR_DRAG_TOOLTIP_AFTER" : "Move to insert after %{memberName}",
		"DIM_EDITOR_DRAG_TOOLTIP_CHILD" : "Move to insert as a child of %{memberName}",
		"DIM_EDITOR_DRAG_TOOLTIP_PARENT" : "Move to insert as a parent of %{memberName}",

		'DIM_EDITOR_ERROR_MSG_CANNOT_CREATE_WIDGET_CONTENT' : "Unable to create the content of this widget. The dimension or hierarchy may have been removed or is inaccessible.",
		'DIM_EDITOR_ERROR_MSG_CANNOT_CREATE_WIDGET_CONTENT_ADMIN' : "Please contact your administrator to ensure you have sufficient rights to view this widget.",

		"MENU_POSITION_ABOVE" : "Before selection",
		"MENU_POSITION_BELOW" : "After selection",
		"MENU_POSITION_CHILD" : "As a child",
		"MENU_POSITION_PARENT" : "As a parent",
		"MENU_PASTE_ABOVE_SELECTION" : "Before selection",
		"MENU_PASTE_BELOW_SELECTION" : "After selection",
		"MENU_PASTE_CHILD" : "As a child",
		"MENU_PASTE_PARENT" : "As a parent",
		"MENU_REMOVE_FROM_PARENT_HIERARCHY" : "From parent",
		"MENU_REMOVE_FROM_HIERARCHY" : "From hierarchy",
		"MENU_DELETE_ATTRIBUTE" : "Delete attribute",
		"MENU_ADD_REMOVE_ATTRIBUTE" : "Add and remove",
		"MENU_FIND_ATTRIBUTE" : "Find value",
		"MENU_CREATE_HIERARCHY" : "Create hierarchy",
		"MENU_ADD_ATTRIBUTE" : "Add attribute",
		"MENU_DELETE_FROM_DIMENSION" : "From dimension",
		"MENU_CREATE_GROUP" : "Add user group",
		"MENU_DELETE_GROUP" : "Delete user group",

		//Dimension Editor Properties Pane
		"DIM_EDITOR_PROPS_DIMENSION_NAME" : "Dimension Name",
		"DIM_EDITOR_PROPS_HIERARCHY_NAME" : "Hierarchy Name",
		"DIM_EDITOR_PROPS_MEMBER_NAME" : "Member Name",
		"DIM_EDITOR_PROPS_INFORMATION" : "Information",
		"DIM_EDITOR_PROPS_TITLE_HIERARCHY" : "Hierarchy Properties",
		"DIM_EDITOR_PROPS_TITLE_MEMBER" : "Member Properties",
		"DIM_EDITOR_PROPS_TIP_HIERARCHY" : "View hierarchy properties",
		"DIM_EDITOR_PROPS_TIP_MEMBER" : "View member properties",
		"DIM_EDITOR_HIERARCHY_SORT_PROPS" : "Hierarchy Sort Properties",
		"DIM_EDITOR_MEMBER_NONE_SELECTED" : "No member is selected",
		"DIM_EDITOR_MEMBER_MULTIPLE_SELECTED" : "Mutiple members are selected",
		"DIM_EDITOR_PROPS_ROOT_MEMBER" : "The member does not have weights as it is a root member",
		"DIM_EDITOR_PROPS_STRING_MEMBER" : "Members of type string cannot have their weights updated",
		"DIM_EDITOR_PROPS_PARENT_HEADER" : "Parent",
		"DIM_EDITOR_PROPS_WEIGHT_HEADER" : "Weight",
		"DIM_EDITOR_PROPS_WARN_TYPE_CHANGE" : "Changing the type may result in data loss.",



		//Over view
		"OVERVIEW_COLUMN" : "Column: ",
		"OVERVIEW_ROW" : "Row: ",
		"OVERVIEW_CONTEXT" : "Context: ",
		"OVERVIEW_OTHERDIMS" : "Other dimensions",
		"OVERVIEW_DRAG_DESCRIPTION" : "Drag individual dimensions to the overview, or tap Add all.",
		"OVERVIEW_BENCH_BUTTONTEXT": "Add All",
		"OVERVIEW_DROPDOWN_EDIT" : "Edit this set",
		"OVERVIEW_DROPDOWN_DELETE": "Remove hierarchy",
		"OVERVIEW_DROPDOWN_VIEWALL" : "View All: ",
		"OVERVIEW_DROPDOWN_SUBSETS" : "Subsets",
		"OVERVIEW_DROPDOWN_LEVELS" : "Levels",
		"OVERVIEW_TILE_HIERARCHYTOOLTIP" : "Hierarchy: ",
		//Model Description
		"SERVER" : "Server: %{server}",
		"CUBE" : "Cube: %{cube}",
		"VIEW" : "View: %{view}",
		"SANDBOX" : "Sandbox: %{sandbox}",

		//Asymmetric
		"ASYMMETRIC_DIALOG_TITLE_ROW" : "Targeted row selection",
		"ASYMMETRIC_DIALOG_TITLE_COLUMN" : "Targeted column selection",
		"ASYMMETRIC_DIALOG_COLUMN_MESSAGE_1" : "Select only those members you want to work with.",
		"ASYMMETRIC_DIALOG_COLUMN_MESSAGE_2" : "When you select more members above, the same selection applies to the members at the lower row for each selected set",
		"ASYMMETRIC_DIALOG_COLUMN_MESSAGE_3" : "You can add more selections",
		"ASYMMETRIC_DIALOG_COLUMN_BUTTON_TEXT" : "Clear",

		"ASYMMETRIC_DIALOG_ROW_MESSAGE_1" : "Select only those members you want to work with.",
		"ASYMMETRIC_DIALOG_ROW_MESSAGE_2" : "When you select more members to the left, the same selection applies to the members on the right in each selected set",
		"ASYMMETRIC_DIALOG_ROW_MESSAGE_3" : "You can add more selections",
		"ASYMMETRIC_DIALOG_ROW_BUTTON_TEXT" : "Clear",

		"ASYMMETRIC_DIALOG_ROW_EXIT_MESSAGE" : "You are about to leave the targeted row selection",
		"ASYMMETRIC_DIALOG_COLUMN_EXIT_MESSAGE" : "You are about to leave the targeted column selection",
		"ASYMMETRIC_DIALOG_EXIT_CONFIRM_MESSAGE" : "Do you want to continue?",

		//Cell validation
		"CELL_INVALID_NUMBER" : "Invalid number",
		"CELL_INVALID_DATE" : "Invalid date",
		"CELL_INVALID_DATETIME" : "Invalid date time value",
		"SELECT_DATE" : "Select date",
		"CELL_INVALID_PERCENTAGE" : "Invalid percentage",
		"CELL_UPDATE_ERROR" : "Data update failed!\n%{details}",
		"CELL_UPDATE_ERROR_LABEL" : "Sorry, Invalid cell update.",
		"CELL_UPDATE_ERROR_SUB_LABEL" : "This might be because the cell is the target of a calculation.  Please contact the owner of the plan.",
		"PICKLIST_CLEAR_OPTION" : "--None--",
		"PICKLIST_SEARCH" : "Search",
		"PICKLIST_SEARCHING" : "Searching...",
		"PICKLIST_NO_RESULTS" : "No results found.",
		"PICKLIST_SELECTION_LIMIT" : "You can only select %{maximumSelections} items.",
		"PICKLIST_LOADING_MORE" : "Loading more results.",
		"PICKLIST_SEARCH_INPUTTOSHORT" : "You must enter at least %{minimumCharacters} character(s).",
		"PICKLIST_SEARCH_INPUTTOLONG" : "You have exceeded search character limit. Please remove %{charactersOverLimit} characters.",
		"PICKLIST_ERRORLOADING" : "Error loading results.",

		//Bench area
		"DEFAULT_BENCH_TITLE" : "Default dimensions",
		"MODIFIED_BENCH_TITLE": "Modified dimensions",

		//EmptyViewInstruction
		"INSTRUCTION_OPENCUBE" : "To get started, open a cube",
		"INSTRUCTION_DRAGDIM" : "You can drag in ",
		"INSTRUCTION_DIM" : " dimensions,",
		"INSTRUCTION_HIERARCHY" : "hierarchies, ",
		"INSTRUCTION_SETS" : " sets,",
		"INSTRUCTION_LEVELS" : " levels, or ",
		"INSTRUCTION_MEMBERS" : " members",
		"INSTRUCTION_GETSTARTED" : "To get started:",
		"INSTRUCTION_OPENBENCH" : "Open the bench ",
		"INSTRUCTION_ANDDRAG" : " and drag ",
		"INSTRUCTION_INTOOPEN" : "into the open data areas.",
		"INSTRUCTION_USETREE" : "Use the tree to add ",

		// Intent dialog strings
		"dlg_IntentResultsTitle": "Search", // replace Gemini string
		"dlg_IntentSearching": "Searching...", // replace Gemini string
		"dlg_IntentCubeTitle" : "Server: %{server} / Cube: %{cube}",
		"dlg_IntentCubeName" : "<b>Server:</b> %{server} / <b>Cube:</b> %{cube}",
		"dlg_IntentViewTitle" : "Server: %{server} / Cube: %{cube} / View: %{view}",
		"dlg_IntentViewName" : "<b>Server:</b> %{server} / <b>Cube:</b> %{cube} / <b>View:</b> %{view}",

		// Snap commands
		"SC_HEADER_TYPE": "Type",
		"SC_HEADER_NAME": "Name",
		"SC_HEADER_DIMENSION": "Dimension",
		"SC_QUOTE_ITEM": "'%{item}'",
		"SC_LIST_SEPARATOR": ", ",
		"SC_AXES_ROWS": "rows",
		"SC_AXES_COLUMNS": "columns",
		"SC_AXES_BOTH": "rows and columns",
		"SC_INPUT_PLACEHOLDER": "Type in your command",

		"SC_BACK_TITLE": "Back",
		"SC_INFO_TITLE": "Toggle information display",

		"SC_HELP_DRILL": "Drills down on the specified members or resets the drill state for the specified dimensions.",
		"SC_DRILL_RESET_AXES": "Reset the drill state for %{axes}",
		"SC_DRILL_RESET_LIST": "Reset the drill state for %{list}",
		"SC_DRILL_DOWN_LIST": "Drill down on %{list}",

		"SC_HELP_FIND": "Finds members matching a filter expression.",
		"SC_FIND_NEXT": "Find next",
		"SC_FIND_PREV": "Find previous",
		"SC_FIND_AXES": "Find members on %{axes} where %{filter}",
		"SC_FIND_HIER": "Find members on dimension %{hier} where %{filter}",
		"SC_FIND_ATTR_CAPTION": "caption",
		"SC_FIND_FILTER_EQ": "%{attribute} equals %{value}",
		"SC_FIND_FILTER_NE": "%{attribute} not equal %{value}",
		"SC_FIND_FILTER_GT": "%{attribute} greater than %{value}",
		"SC_FIND_FILTER_GE": "%{attribute} greater than or equal to %{value}",
		"SC_FIND_FILTER_LT": "%{attribute} less than %{value}",
		"SC_FIND_FILTER_LE": "%{attribute} less than or equal to %{value}",
		"SC_FIND_FILTER_ST": "%{attribute} starts with %{value}",
		"SC_FIND_FILTER_EN": "%{attribute} ends with %{value}",
		"SC_FIND_FILTER_CO": "%{attribute} contains %{value}",
		"SC_FIND_FILTER_AND": "%{filter1} and %{filter2}",
		"SC_FIND_FILTER_OR": "%{filter1} or %{filter2}",
		"SC_FIND_RESULT": "Showing result %{current} of %{total}",

		"SC_HELP_HIDE": "Hides the specified members.",
		"SC_HIDE": "Hide %{list}",

		"SC_HELP_KEEP": "Retains the specified members.",
		"SC_KEEP": "Keep %{list}",

		"SC_HELP_LEVEL": "Expands dimensions to the specified level. Use 0 to expand to leaves.",
		"SC_LEVEL_AXES": "Expand levels on %{axes} to level %{depth}",
		"SC_LEVEL_AXES_LEAF": "Expand levels on %{axes} to the leaf level",
		"SC_LEVEL_HIER": "Expand dimension %{dim} to level %{depth}",
		"SC_LEVEL_HIER_LEAF": "Expand dimension %{dim} to the leaf level",
		"SC_LEVEL_BY_NAME": "For level name %{name} expand to that level, or for dimension name %{name} expand to the leaf level",
		"SC_LEVEL_RESULT_LN": "Expand dimension %{dim} to level %{name}",
		"SC_LEVEL_RESULT_HN": "Expand dimension %{dim} to the leaf level",

		"SC_HELP_SELECT": "Select named members, levels and sets.",
		"SC_SELECT": "Select %{list}",
		"SC_SELECTED": "Selected %{list}",
		"SC_SELECT_MEMBER": "'%{match}' on dimension '%{hierCaption}'",
		"SC_SELECT_LEVEL": "level '%{match}' on dimension '%{hierCaption}'",
		"SC_SELECT_SET": "set '%{match}' on dimension '%{hierCaption}'",

		"SC_HELP_SORT": "Sort rows and columns by label or value.",
		"SC_SORT_DIR_ASC": "ascending",
		"SC_SORT_DIR_DESC": "descending",
		"SC_SORT_HIER": "hierarchically",
		"SC_SORT_BREAK": "breaking",
		"SC_SORT_LABEL_AXES": "Sort by label %{direction} %{hierarchical} on %{axes}",
		"SC_SORT_LABEL_HIERS": "Sort by label %{direction} %{hierarchical} on %{list}",
		"SC_SORT_VALUE": "Sort by value %{direction} %{hierarchical} for member %{list}",
		"SC_SORT_TBD": "Sort %{direction} %{hierarchical} for %{list}",
		"SC_SORT_CLEAR_AXES": "Clear sorting on %{axes}",
		"SC_SORT_CLEAR_HIERS": "Clear sorting on %{list}",

		"SC_HELP_SWAP": "Swaps two dimensions. If no dimensions are specified, swaps rows and columns.",
		"SC_SWAP_HIERS": "Swap %{name1} and %{name2}",
		"SC_SWAP_RC": "Swap rows and columns",

		"SC_HELP_TOTALS": "Show leading or trailing totals or hide totals for the given dimensions or axes.",
		"SC_TOTALS_LEADING": "Show leading totals",
		"SC_TOTALS_TRAILING": "Show trailing totals",
		"SC_TOTALS_HIDE": "Hide totals",
		"SC_TOTALS_AXES": "%{totals} on %{axes}",
		"SC_TOTALS_HIERS": "%{totals} on %{list}",

		"SC_HELP_UNHIDE": "Unhides any hidden members on the specified dimensions or axes.",
		"SC_UNHIDE_AXES": "Unhide members on %{axes}",
		"SC_UNHIDE_HIERS": "Unhide members on %{list}",

		"SC_HELP_ZEROSUPPRESSION": "Controls zero suppression on the rows and columns.",
		"SC_ZERO_ON": "Enable zero suppression for %{axes}",
		"SC_ZERO_OFF": "Disable zero suppression for %{axes}",

		"SC_SEARCHING": "Resolving command parameters...",
		"SC_EXECUTING": "Executing...",
		"SC_NO_HITS": "'%{query}' not found.",
		"SC_RESOLVE_HITS": "Press enter or double-click on the item matching '%{query}'.",
		"SC_TYPE_ELEMENT": "Member",
		"SC_TYPE_SUBSET": "Set",
		"SC_TYPE_LEVEL": "Level",
		"SC_TYPE_HIERARCHY": "Dimension",

		"SC_FIND_NOT_ACTIVE": "No results from a find command are available.",
		"SC_FIND_NO_RESULTS": "No results found.",
		"SC_SORT_INVALID_PARAMS": "A mix of hierarchies and members were specified.",
		"SC_SORT_BAD_TUPLE": "To sort by value you must specify a member for every hierarchy on the axis.",

		"SC_ERR_EXPECTED_EOL": "Looking for %{list}",
		"SC_ERR_EXPECTED": "Looking for %{list} but found '%{found}' at position %{pos}.",
		"SC_ERR_TYPE_END": "no more input",
		"SC_ERR_OTHER_LIST_SEPARATOR": "a list separator",
		"SC_ERR_OTHER_NAME": "a name",
		"SC_ERR_OTHER_LIST_OF_NAMES": "a list of names",
		"SC_ERR_OTHER_OPTIONS": "command options",
		'SC_ERR_OTHER_WHITESPACE': "space",
		'SC_ERR_OTHER_MEMBER_NAME': "a member name",
		'SC_ERR_OTHER_MINUS': "- (minus)",
		'SC_ERR_OTHER_DEPTH': "level depth",
		"SC_ERR_OTHER_FILTER": "filter expression",
		"SC_ERR_OTHER_ATTRIBUTE_NAME": "attribute name",
		"SC_ERR_OTHER_COMPARISON_OPERATOR": "comparison operator",
		"SC_ERR_OTHER_FILTER_VALUE": "filter value",

		"dlg_ConfirmNo" : "No",
		"dlg_ConfirmYes" : "Yes",
		"dlg_SandboxCommit" : "Are you sure that you want the data in this sandbox to become your base?",
		"dlg_SandboxDescription" : "Use sandboxes to try out different business scenarios.",
		"dlg_SandboxDeleteDescription" : "Select sandboxes to remove",
		"dlg_SandboxCreate" : "Create",
		"dlg_SandboxDelete" : "Delete",
		"dlg_SandboxCancel" : "Cancel",
		"dlg_SandboxTitle" : "Sandboxes",
		"dlg_SandboxNewPlaceholder" : "New sandbox name",
		"dlg_SandboxActionCreateUsing": "Create from",
		"dlg_SandboxActionCreate": "Create",
		"dlg_SandboxActionDelete": "Delete",
		"dlg_InvalidSandboxName" : "Please enter a valid sandbox name.",
		"dlg_SandboxAlreadyExists" : "Sandbox already exists.",
		"dlg_ErrorCreatingSandbox" : "Error creating sandbox.",
		"dlg_ErrorDeletingSandbox" : "Error deleting sandbox.",

		// save view
		"SAVEVIEW_SAVEAS" : "Save as",
		"SAVEVIEW_SAVE" : "Save",
		"SAVEVIEW_DO_YOU_WANT_OVERWRITE" : "Do you want to overwrite?",
		"SAVEVIEW_VIEW_EXIST_ALREADY" : "The view '%{viewname}' exists already.",
		"SAVEVIEW_VIEW_SAVED" : "Your view is saved as \"%{viewname}\" in the cloud content store.",
		"SAVEVIEW_ORIGINAL_VIEW" : "Original view",
		"SAVEVIEW_SERVER" : "Server",
		"SAVEVIEW_CUBE" : "Cube",
		"SAVEVIEW_TAGS" : "Tags",
		"SAVEVIEW_DESCRIPTION" : "Description",
		"SAVEVIEW_EMPTY_NAME" : "Please provide a name.",
		"SAVEVIEW_TAGS_MAXLENGTH" : "Your tags length is %{tags} characters, it exceeds the maximum length of %{max} characters.",
		"SAVEVIEW_DESCRIPTION_MAXLENGTH" : "Your description length is %{description}, it exceeds the maximum length of %{max} characters.",
		"SAVEVIEW_SAVED_SUCCESSFULLY" : "Your view \"%{viewname}\" has been saved successfully.",
		//Error
		"TM1MDV_ERROR_TITLE" : "Error",
		"TM1MDV_ERROR_UNKNOWN" : "Unknown error encountered.",

		//nav
		"NAV_DIALOG_TITLE" :"Select asset",
		"NAV_DIALOG_DESCRIPTION" :"Select an asset to define the navigation target.",
		"NAV_DIALOG_FOOT" :"Selected:",
		"NAV_FOLDER_DES" :"Location",
		"NAV_BOOK_DES" : "Books",
		"NAV_TAB_DES" : "Tabs",
		"NAV_NONE" : "None",
		"NAV_DIALOG_SET" :"Select",
		"NAV_DIALOG_CANCEL":"Cancel",
		//hierarchy Tile Context Menu
		"HIERARCHY_HIDE_FROM_VIEW": "Hide from view",
		"HIERARCHY_REMOVE_CURRENT": "Remove this hierarchy",
		"HIERARCHY_REPLACE_CURRENT": "Replace this hierarchy...",
		"HIERARCHY_ADD_ANOTHER": "Add related hierarchy...",
		"HIERARCHY_DIALOG_INSERT_BUTTON" : "Insert",
		"HIERARCHY_DIALOG_REPLACE_BUTTON": "Replace",
		"HIERARCHY_DIALOG_CANCEL_BUTTON" : "Cancel",
		"HIERARCHY_ADD_TITLE": "Add related hierarchy",
		"HIERARCHY_REPLACE_TITLE": "Replace this hierarchy",
		"HIERARCHY_DIMENSIONS_LABEL": "Dimensions: ",


		// Synchronization Tile Widget
		"SYNC_TILE_SETTINGS_TITLE" : "Selector Properties",
		"SYNC_TILE_TYPE" : "Selection Type",
		"SYNC_TILE_TYPE_SET" : "Sets and Levels",
		"SYNC_TILE_TYPE_MEMBER" : "Members",

		//calculation dialog titles
		"DIALOG_CALCULATIONTITLE_CREATE" : "Create - %{contextLabel}",
		"DIALOG_CALCULATIONTITLE_RENAME" : "Rename a calculation",
		"DIALOG_CALCULATIONTITLE_SUMMARIZEALL" : "Summarize all",
		//default calculation names formulated, if none supplied
		"NAME_CALCULATION_RANK" : "Rank",
		"NAME_CALCULATION_ABSOLUTE_VALUE" : "ABS",
		"NAME_CALCULATION_PERCENT_OF_TOTAL" : "Percentage (%) of total",
		"NAME_CALCULATION_PERCENT_OF_PARENT" : "Percentage (%) of parent",
		"NAME_CALCULATION_PERCENT_OF" : "% Of",
		"NAME_CALCULATION_PLUS": "plus",
		"NAME_CALCULATION_MULTIPLY": "times",
		"NAME_CALCULATION_DIVIDE": "divide by",
		"NAME_CALCULATION_MINUS": "minus",
		"NAME_CALCULATION_PERCENT_CHANGE": "% of change",
		"NAME_CALCULATION_VAR": "var",
		"NAME_CALCULATION_SUM": "Σ",
		"NAME_CALCULATION_AVG": "avg",
		"NAME_CALCULATION_MEDIAN": "median",
		"NAME_CALCULATION_STDEV": "stdev",
		"NAME_CALCULATION_MAX": "max",
		"NAME_CALCULATION_MIN": "min",
		"NAME_CALCULATION_SEPARATOR_AND": "and",
		"DYNAMIC_CALCULATION_SUM": "Sum (all)",
		"DYNAMIC_CALCULATION_AVG": "Average (all)",
		"DYNAMIC_CALCULATION_MEDIAN": "Median (all)",
		"DYNAMIC_CALCULATION_STDEV": "Standard deviation (all)",
		"DYNAMIC_CALCULATION_MAX": "Maximum (all)",
		"DYNAMIC_CALCULATION_MIN": "Minimum (all)",
		"DYNAMIC_CALCULATION_VAR": "Variance (all)",
		"RANGE_CALCULATION_SUM": "Range sum",
		"RANGE_CALCULATION_AVG": "Range avg",
		"RANGE_CALCULATION_MEDIAN": "Range median",
		"RANGE_CALCULATION_STDEV": "Range stdev",
		"RANGE_CALCULATION_MAX": "Range max",
		"RANGE_CALCULATION_MIN": "Range min",
		"RANGE_CALCULATION_VAR": "Range var",

		"CALCULATION_NAME_INVALID":"Invalid calculation name.",
		"CALCULATION_CREATE_ERROR":"Error creating calculation.",
		"CALCULATION_INPUT_NAME_LABEL":"Name",
		"CALCULATION_INPUT_NAME_PLACEHOLDER":"New calculation name",
		"CALCULATION_INPUT_NAME_PLACEHOLDER_DYNAMIC":"Summarize all",
		"CALCULATION_MEMBER_PLACEHOLDER":"member",
		"CALCULATION_NUMBER_NAME":"Number",

		"CLIPBOARD_INVALID_SINGLE_RANGE_SELECTION":"The clipboard action could not be performed. Select a single range and try again.",
		"CLIPBOARD_INVALID_SINGLE_ITEM_SELECTION":"The clipboard action could not be performed. Select a single item and try again.",
		"CLIPBOARD_NOT_PERMITTED_FOR_YOUR_SELECTION":"Clipboard action is not permitted for your current selection.",
		"CLIPBOARD_CUT_NOT_PERMITTED":"Clipboard cut action is not permitted.",
		"CLIPBOARD_COPY_NOT_PERMITTED":"Clipboard copy action is not permitted.",
		"CLIPBOARD_NO_SELECTION_HANLDER":"Clipboard actions are only permitted for items with selection capability.",
		"CLIPBOARD_CUT_NO_CONTENT":"Error getting content for clipboard cut action.",
		"CLIPBOARD_COPY_NO_CONTENT":"Error getting content for clipboard copy action.",
		"CLIPBOARD_CUT_ERROR":"Error performing clipboard cut action.",
		"CLIPBOARD_COPY_ERROR":"Error performing clipboard copy action.",
		"CLIPBOARD_BROWSER_COPY_ERROR":"Your browser did not allow clipboard access. Data not copied to clipboard.",
		"CLIPBOARD_BROWSER_CUT_ERROR":"Your browser did not allow clipboard access. Data not cut to clipboard.",
		"CONFIRM_CLIPBOARD_LARGER_THEN_SELECTION":"Your selection range is smaller than the content in the clipboard. Data outside your selection will also be modified. Do you wish to continue with paste?",
		"CLIPBOARD_ALL_DATA_NOT_ON_VISIBLE_PAGE":"All the data for your selection is not available on the current page. Unable to perform clipboard action. Please make a new selection.",
		"CLIPBOARD_SELECTION_NOT_ON_VISIBLE_PAGE":"Your selection is not on the current page. Unable to perform clipboard action. Please scroll to your selection or make a new selection.",

		"HIERARCHY_DELETE_SUCCESS" : "Hierarchy \"%{hierarchy}\" successfully deleted.",

		// selection
		"SELECTION_LABEL_ITEM_DELIMITER" : ",", // in grid widget, select individual members, right click to launch context menu, items in top label use this as delimiter
		"SELECTION_LABEL_RANGE_DELIMITER" : " - ", // in grid widget, use shift to select a range of members, right click to launch context menu, range info in top label use this as delimiter
		"SELECTION_LABEL_VALUE_DELIMITER" : ", ", // in grid widget, use shift to select some cells, right click to launch context menu, selected values use this as delimiter

		//Generic Close
		"CLOSE": "Close",
		"SORRY_SOMETHING_WENT_WRONG_TITLE":"Sorry, something went wrong",
		//set editor paste
		"SETEDITOR_PASTE_ERROR_NONE_MATCH" : "None of the items you pasted match with existing members in this dimension.",
		"SETEDITOR_PASTE_ERROR_NOTALL_MATCH" : "Not all of the items you pasted match with existing members in this dimension.",
		"SETEDITOR_PASTE_ERROR_MATCH_ON_NAMES" : "You can paste only names of members that already exist in the parent dimension.",
		"SETEDITOR_PASTE_ERROR_NUMITEMS" : "%{numItems} items do not match",
		"VIEWMORE": "View More",
		"VIEWLESS": "View Less",

	},

	'de': true,
	'es': true,
	'fr': true,
	'it': true,
	'ja': true,
	'pt-br': true,
	'zh-cn': true,
	'zh-tw': true,
	'gl': true
});

// UFRID:0BE1DEC7-EAFF-4BEB-9860-14A561A5AB35
